"""Generate the documentation schemas; runtime uses narrow explicit validators."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
STR={'type':'string'}; ID={'type':'string','pattern':'^[0-9a-f]{32}$'}; SHA={'type':'string','pattern':'^[0-9a-f]{64}$'}; LABEL={'type':'string','pattern':'^[A-Za-z0-9_-]{1,64}$'}; TIME={'type':'number','minimum':0}
SCOPE={'contract':{'const':'file-ipc-portable/1'},'deployment_id':ID,'run_id':ID,'owner_id':LABEL}
ACTOR={**SCOPE,'role':{'enum':['desktop','broker']},'worker_id':LABEL,'assignment_id':ID,'epoch':{'type':'integer','minimum':1,'maximum':3}}
def obj(props,required=None):return {'type':'object','properties':props,'required':list(props) if required is None else required,'additionalProperties':False}
def write(name,schema):
 schema={'$schema':'https://json-schema.org/draft/2020-12/schema','title':name,'$comment':'Portable contract v1. Runtime cross-file scope, hashing, fencing and time rules are additionally enforced by code.',**schema}
 (ROOT/'schemas'/(name+'.schema.json')).write_text(json.dumps(schema,indent=2)+'\n')
assignment=obj({**ACTOR,'issued':TIME,'expires':TIME,'status':{'enum':['active','closed']},'native_capability':{'enum':['operator_attested','not_required']}})
write('assignment',assignment)
write('heartbeat',obj({**ACTOR,'expires':TIME,'at':TIME,'state':{'enum':['ready','busy','closed']}}))
job=obj({'id':ID,'request_sha256':SHA,'lease_epoch':{'type':'integer','minimum':1,'maximum':3},'state':{'enum':['completed','failed']},'completion_sha256':SHA})
write('receipt',obj({**ACTOR,'receipt_id':ID,'event':{'enum':['ready','claimed','inference_started','completed','failed','stopped','blocked','worker_expired','broker_crash','recovery_resolved']},'code':{'enum':['none','user_stop','auth_required','permission_denied','configuration_error','ambiguous_dispatch','worker_expired','broker_crash','deadline','service_closed','request_limit','normal_exit']},'job':{'anyOf':[{'type':'null'},job]},'created':TIME,'content_sha256':SHA,'notification':{'const':'written_outbox'}}))
write('acknowledgment',obj({**SCOPE,'receipt_id':ID,'content_sha256':SHA,'via':{'enum':['manual_parent','parent_tool']},'evidence':{'type':'string','pattern':'^[A-Za-z0-9_:/.-]{1,256}$'},'meaning':{'const':'parent acknowledgment recorded; this helper sent no notification'}}))
write('result',obj({'kind':{'const':'message'},'text':{'type':'string','minLength':1,'maxLength':131072,'description':'Runtime also caps the full encoded UTF-8 JSON envelope at 131072 bytes.'}}))
policy=obj({'max_requests':{'type':'integer','minimum':1,'maximum':3},'max_broker_starts':{'type':'integer','minimum':1,'maximum':3},'max_desktop_starts':{'const':1},'request_seconds':{'const':180},'lease_seconds':{'const':60},'claim_wait_seconds':{'const':20}})
write('deployment',obj({**SCOPE,'created':TIME,'expires':TIME,'scope':{'const':'text_only'},'notification':{'enum':['outbox_only','parent_tool_attested']},'policy':policy,'paths':obj({'queue':{'type':'string','pattern':'^runs/[0-9a-f]{32}/queue$'},'cli':{'type':'string','pattern':'^runs/[0-9a-f]{32}/isolated-cli$'},'evidence':{'const':'evidence'}})}))
write('recovery',obj({'contract':SCOPE['contract'],'deployment_id':ID,'owner_id':LABEL,'action':{'enum':['await_operator','assign_replacement_broker']},'reason':{'type':['string','null']},'executed':{'const':False},'notification_delivered':{'const':False},'desktop_restart':{'const':'new deployment directory only; no replay of prior jobs'}}))
write('handoff',obj({**SCOPE,'role':{'enum':['desktop','broker']},'local_package_path':STR,'local_deployment_root':STR,'assignment_relative_path':{'type':'string','pattern':'^evidence/[A-Za-z0-9_.-]+\\.json$'},'instructions':{'enum':['START_HERE.zh-CN.md','BROKER_HANDOFF.zh-CN.md','HANDOFF_TEST.zh-CN.md']},'expires':TIME,'max_requests':{'type':'integer','minimum':1,'maximum':3},'scope':{'const':'text_only'},'native_inference':{'enum':['operator_attested','not_required']},'parent_notification':{'enum':['outbox_only','parent_tool_attested']},'automatic_task_spawn':{'const':False}}))
contract={'contract':'file-ipc-portable/1','protocol_scope':'text_only','roles':{'parent_driver':{'executes':'uses only actually available supported task tools or an explicit operator; schedules bounded workers','detects':['actual tool availability and schema','task outcome via supported read/status when available'],'must_not_assume':['outbox writes wake an agent','environment disconnection ends a task','Python has native task tools','exactly-once task dispatch','unattended delivery SLA']},'desktop':{'runs':['official Codex','loopback facade','isolated launcher'],'owns':['fresh queue path','fresh isolated CLI path','its own child process lifecycle'],'network':'CLI and facade must share a reachable loopback environment'},'broker':{'runs':['active native inference agent','bounded data wrappers'],'owns':['current assignment epoch','private metadata ticket','exact model text result'],'must_not_run':['payload tools or shell','default external provider','fabricated inference output']}},'state_dimensions':['deployment identity','role assignment epoch','queue lease epoch','inference dispatch state','HTTP delivery state','receipt observation state'],'notification_states':['written_outbox','read_observer','acknowledged_parent'],'retry_policy':{'desktop':'new deployment only; never replay old queue','broker':'bounded starts; expired role and task lease; no started ambiguous inference until explicitly resolved','blocked':['user_stop','auth_required','permission_denied','configuration_error']},'schema_dialect':'https://json-schema.org/draft/2020-12/schema','native_task_api':'none implemented','network_listener':'127.0.0.1 only'}
(ROOT/'ROLE_CONTRACT.json').write_text(json.dumps(contract,ensure_ascii=False,indent=2)+'\n')
queue_job=obj({'id':ID,'owner':LABEL,'session':LABEL,'request_sha256':SHA,'created':TIME,'deadline':TIME,'state':{'const':'running'},'attempts':{'type':'integer','minimum':1,'maximum':3},'lease_epoch':{'type':'integer','minimum':1,'maximum':3},'delivery':{'const':'waiting'},'lease':ID,'lease_until':TIME})
write('ticket',obj({'contract':SCOPE['contract'],'deployment_id':ID,'run_id':ID,'assignment_id':ID,'worker_epoch':{'type':'integer','minimum':1,'maximum':3},'job':queue_job}))
